BlockSize = 15
HistogramDepth = 256
ClippedContrast = 0.08
MinAbsoluteContrast = 17 / 255.0
MinRelativeContrast = 0.34
RelativeContrastSample = 168568
RelativeContrastPercentile = 0.49
MaskVoteRadius = 7
MaskVoteMajority = 0.51
MaskVoteBorderDistance = 4
BlockErrorsVoteRadius = 1
BlockErrorsVoteMajority = 0.7
BlockErrorsVoteBorderDistance = 4
MaxEqualizationScaling = 3.99
MinEqualizationScaling = 0.25
MinOrientationRadius = 2
MaxOrientationRadius = 6
OrientationSplit = 50
OrientationsChecked = 20
OrientationSmoothingRadius = 1
ParallelSmoothingResolution = 32
ParallelSmoothingRadius = 7
ParallelSmoothingStep = 1.59
OrthogonalSmoothingResolution = 11
OrthogonalSmoothingRadius = 4
OrthogonalSmoothingStep = 1.11
BinarizedVoteRadius = 2
BinarizedVoteMajority = 0.61
BinarizedVoteBorderDistance = 17
InnerMaskBorderDistance = 14
MaskDisplacement = 10.06
MinutiaCloudRadius = 20
MaxCloudSize = 4
MaxMinutiae = 100
SortByNeighbor = 5
EdgeTableNeighbors = 9
ThinningIterations = 26
MaxPoreArm = 41
ShortestJoinedEnding = 7
MaxRuptureSize = 5
MaxGapSize = 20
GapAngleOffset = 22
ToleratedGapOverlap = 2
MinTailLength = 21
MinFragmentLength = 22
MaxDistanceError = 13
        public const float MaxAngleError = FloatAngle.Pi / 180 * 10
MaxGapAngle = Math.PI / 180 * 45
RidgeDirectionSample = 21
RidgeDirectionSkip = 1
MaxTriedRoots = 70
MinRootEdgeLength = 58
MaxRootEdgeLookups = 1633
MinSupportingEdges = 1
DistanceErrorFlatness = 0.69
AngleErrorFlatness = 0.27
MinutiaScore = 0.032
MinutiaFractionScore = 8.98
MinutiaTypeScore = 0.629
SupportedMinutiaScore = 0.193
EdgeScore = 0.265
DistanceAccuracyScore = 9.9
AngleAccuracyScore = 2.79
ThresholdFmrMax = 8.48
ThresholdFmr2 = 11.12
ThresholdFmr10 = 14.15
ThresholdFmr100 = 18.22
ThresholdFmr1000 = 22.39
ThresholdFmr10K = 27.24
ThresholdFmr100K = 32.01